### ISSUE TITLE
JOSS Review [crvernon]:  Readme code example incorrect

### ISSUE THREAD

**Issue by crvernon** [niceume/datasailr#12]
**Review reference:** openjournals/joss-reviews#3166

The example in your README does not render the output documented:  see https://github.com/niceume/datasailr#code-example

Consider using the same example as the one you used in the [paper.md](https://github.com/niceume/datasailr/blob/joss_submission/paper.md)

**Comment by niceume** [comment]
Thank you for your comment! The example code and its output are updated.  a783d56c98ac182bf6ff9f42fe698b86533b1c7a
