### ISSUE TITLE
JOSS Review [crvernon]: Include masked regex behavior in documentation

### ISSUE THREAD

**Issue by crvernon** [niceume/datasailr#13]
**Review reference:** openjournals/joss-reviews#3166

It should be noted in the documentation that a duplicated value in a regex query string will use the first assignment in the subsequent conditional statement without notifying the user that a multiple value exists.  See the `Hornet` value that I added in for both the `usa` and `japan` assignments:

```
germany = re/(^Merc|^Porsche|^Volvo)/
usa = re/(^Hornet|^Cadillac|^Lincoln|^Chrysler|^Dodge|^AMC|^Camaro|^Chevrolet|^Pontiac|^Ford)/
japan = re/(^Mazda|^Datsun|^Honda|^Toyota|^Hornet)/
```

This will assign `Hornet` to `usa` when using your following conditional:

```
if ( _rowname_ =~ germany ) { country = "Germany" ; type = rexp_matched(1); }
else if( _rowname_ =~ usa ) { country = "USA"  ; type = rexp_matched(1);  }
else if( _rowname_ =~ japan ) { country = "Japan"  ; type = rexp_matched(1); }
else { country = "Other" }
```

This is expected when only considering the conditional statement; however, it could introduce unexpected behavior if the regex queries are incorrectly constructed (e.g., if `Hornet` has been incorrectly assigned to `usa` in the above).

**Comment by niceume** [comment]
Thank you for your comment!

Even when ^Hornet  appears in regular expressions for both usa and japan, they both work. (i.e. they do not mask each other.)

The following code shows that ^Hornet in usa and ^Hornet in japan work.

```
library(datasailr)
data(mtcars)

sail(mtcars, '
germany = re/(^Merc|^Porsche|^Volvo)/
usa = re/(^Hornet|^Cadillac|^Lincoln|^Chrysler|^Dodge|^AMC|^Camaro|^Chevrolet|^Pontiac|^Ford)/
japan = re/(^Mazda|^Datsun|^Honda|^Toyota|^Hornet)/

_rowname_ =~ germany
type_germany = rexp_matched(1)
_rowname_ =~ usa
type_usa = rexp_matched(1)
_rowname_ =~ japan
type_japan = rexp_matched(1)
')
```

**Comment by crvernon** [comment]
> Even when ^Hornet appears in regular expressions for both usa and japan, they both work. (i.e. they do not mask each other.)
> The following code shows that ^Hornet in usa and ^Hornet in japan work.

I agree that this situation works; however, when the assignment occurs for a common field (e.g., `type`) only the first occurrence of the value (`Hornet`) will be recognized.

**Comment by niceume** [comment]
> when the assignment occurs for a common field (e.g., type) only the first occurrence of the value (Hornet) will be recognized.

This is true when regular expression matching is conducted in if-else's conditions. (you already seem to have mentioned)

In the following code, the last regular expression matching result overwrites the previous results, because those matching results are assigned to the same field (`type`).

```
library(datasailr)
data(mtcars)

sail(mtcars, '
germany = re/(^Merc|^Porsche|^Volvo)/
usa = re/(^Hornet|^Cadillac|^Lincoln|^Chrysler|^Dodge|^AMC|^Camaro|^Chevrolet|^Pontiac|^Ford)/
japan = re/(^Mazda|^Datsun|^Honda|^Toyota|^Hornet)/

_rowname_ =~ germany
type = rexp_matched(1)
_rowname_ =~ usa
type = rexp_matched(1)
_rowname_ =~ japan
type = rexp_matched(1)
')
````

I am sorry if I misunderstand what you are saying. 

What I am saying is that whether the first occurrence or the last occurrence takes effect does not come from regular expression's feature. It comes from how the code is executed.

**Comment by crvernon** [comment]
> What I am saying is that whether the first occurrence or the last occurrence takes effect does not come from regular expression's feature. It comes from how the code is executed.

I agree.  I didn't want users to be misled by assumptions that there would be some error raised if there were errors within their regular expressions, in terms of duplicated values in the query string.  Since these query strings will likely be constructed manually, I believe they are prone to these types user error.  

If you believe that the current representation of how this functions is sufficiently represented in your documentation, I will close the issue.

**Comment by niceume** [comment]
I understand. When I make tutorials, I will keep it in mind. Thank you very much for your comments!
