### ISSUE TITLE
State target audience 

### ISSUE THREAD

**Issue by DrMattG** [niceume/datasailr#4]
(https://github.com/openjournals/joss-reviews/issues/3166)
A statement of need: Need to "...clearly state what problems the software is designed to solve and who the target audience is". 

I think you could add some more to the documentation (README) to state who the target audience are. You state it nicely in the manuscript - i.e. users who are used to SAS

**Comment by niceume** [comment]
Description and motivation parts are updated to clarify target audience in 617b78da8949a8313f73448ca900dc19bdff747d .
