### ISSUE TITLE
JOSS Review [crvernon]: GitHub actions for CI

### ISSUE THREAD

**Issue by crvernon** [niceume/datasailr#9]
**Review reference:** openjournals/joss-reviews#3166 

Consider setting up CI for your test suite to run via GitHub actions or the like per push and/or PR on at least one OS.

See https://github.com/r-lib/actions for reference.  There are other resources available as well.

**Comment by niceume** [comment]
Thank you very much for your suggestion!

To build this package,  additional tools such as autotools, bison and flex are required. Just using the r-lib/actions, build does not succeed. At now, I do not have  enough knowledge to set up additional tools on Github actions. 

This package is accepted by CRAN, and it shows this package is successfully built on multiple platforms.  https://cran.r-project.org/web/checks/check_results_datasailr.html

**Comment by crvernon** [comment]
This approach seems reasonable for now.  Thanks!
